[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
max_concurrency = 5

[calicoctl]
source = "github"
github = "projectcalico/calico"
use_latest_release = true

[chart-testing]
source = "github"
github = "helm/chart-testing"
use_latest_release = true

[dcnnt]
source = "github"
github = "cyanomiko/dcnnt-py"
use_latest_tag = true

[docker-ls]
source = "github"
github = "mayflower/docker-ls"
use_latest_release = true

[etcdadm]
source = "github"
github = "kubernetes-sigs/etcdadm"
use_latest_release = true

[golang-mockery]
source = "github"
github = "vektra/mockery"
use_latest_release = true

[golangci-lint]
source = "github"
github = "golangci/golangci-lint"
use_latest_release = true

[helm-2to3]
source = "github"
github = "helm/helm-2to3"
use_latest_release = true

[helm-diff]
source = "github"
github = "databus23/helm-diff"
use_latest_release = true

[helm-edit]
source = "github"
github = "mstrzele/helm-edit"
use_latest_release = true

[helm-push]
source = "github"
github = "chartmuseum/helm-push"
use_latest_release = true

[hurl-rs]
source = "github"
github = "Orange-OpenSource/hurl"
use_latest_release = true

[ionosctl]
source = "github"
github = "ionos-cloud/ionosctl"
use_latest_release = true

[jsonnet-bundler]
source = "github"
github = "jsonnet-bundler/jsonnet-bundler"
use_latest_release = true

[kind]
source = "github"
github = "kubernetes-sigs/kind"
use_latest_release = true

[ksd]
source = "github"
github = "mfuentesg/ksd"
use_latest_release = true

[kubectl-neat]
source = "github"
github = "itaysk/kubectl-neat"
use_latest_release = true

[mixtool]
source = "github"
github = "monitoring-mixins/mixtool"
branch = "main"

[python3-yamale]
source = "github"
github = "23andMe/Yamale"
use_latest_release = true

[sonobuoy]
source = "github"
github = "vmware-tanzu/sonobuoy"
use_latest_release = true

[spruce]
source = "github"
github = "geofffranks/spruce"
use_latest_release = true

[svu]
source = "github"
github = "caarlos0/svu"
use_latest_release = true

[vanity_gpg]
source = "github"
github = "RedL0tus/VanityGPG"
use_latest_tag = true

[vim-ansible-git]
source = "github"
github = "pearofducks/ansible-vim"
use_latest_release = true

[vim-rec]
source = "github"
github = "zaid/vim-rec"
use_latest_release = true

[vacuum]
source = "github"
github = "daveshanley/vacuum"
use_latest_release = true

[vt-cli]
source = "github"
github = "VirusTotal/vt-cli"
use_latest_release = true
